spring:
  datasource:
    url: "jdbc:mysql://avnadmin:AVNS_NdXo9INdYdQ5-fw4OyA@garan123-caohuythinh-3c18.c.aivencloud.com:13814/defaultdb?ssl-mode=REQUIRED"
    username: "avnadmin"
    password: "AVNS_NdXo9INdYdQ5-fw4OyA"

  #JPA Settings
  jpa.hibernate.ddl_auto: update